console.log("1", typeof 1)
console.log("1.2", typeof 1.2)
console.log("Danilo", typeof "Danilo")
console.log("1", typeof "1")
console.log("true", typeof true)
console.log("string + number", "2" + 2)
console.log("string + number", typeof("2" + 2))